package com.example.appdegestindegastos.data.model

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents the "categories" table in the Room database.
 * Each instance of this class corresponds to a single row in the table.
 *
 * @property id The unique identifier for the category, automatically generated by the database.
 * @property type The name or type of the category (e.g., "Food", "Transport").
 */
@Entity(tableName = "categories")
data class CategoryEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    val type: String
)
