package com.example.appdegestindegastos.data.model

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents the "expenses" table in the Room database.
 * Each instance of this class corresponds to a single row in the table.
 *
 * @property id The unique identifier for the expense, automatically generated by the database.
 * @property amount The monetary value of the expense.
 * @property description A textual description detailing the expense.
 * @property date The timestamp indicating when the expense occurred.
 * @property categoryId A foreign key that links this expense to a category in the "categories" table.
 */
@Entity(tableName = "expenses")
data class ExpenseEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    val amount: Double,
    val description: String,
    val date: Long,
    val categoryId: Long
)
